"""
Django management command to set up automated backups using cron
"""
import os
import subprocess
from django.core.management.base import BaseCommand
from django.conf import settings


class Command(BaseCommand):
    help = 'Set up automated backups every 6 hours using system cron'

    def add_arguments(self, parser):
        parser.add_argument(
            '--interval',
            type=str,
            default='6h',
            choices=['1h', '3h', '6h', '12h', '24h'],
            help='Backup interval (default: 6h)'
        )
        parser.add_argument(
            '--backup-dir',
            type=str,
            default='backups',
            help='Backup directory (default: backups)'
        )
        parser.add_argument(
            '--max-backups',
            type=int,
            default=20,
            help='Maximum number of backups to keep (default: 20)'
        )

    def handle(self, *args, **options):
        interval = options['interval']
        backup_dir = options['backup_dir']
        max_backups = options['max_backups']
        
        # Get current project directory
        project_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
        manage_py = os.path.join(project_dir, 'manage.py')
        python_path = subprocess.check_output(['which', 'python']).decode().strip()
        
        # Create backup directory if it doesn't exist
        full_backup_dir = os.path.join(project_dir, backup_dir)
        if not os.path.exists(full_backup_dir):
            os.makedirs(full_backup_dir)
            self.stdout.write(f'Created backup directory: {full_backup_dir}')
        
        # Convert interval to cron format
        cron_schedule = self.get_cron_schedule(interval)
        
        # Create backup script
        backup_script = self.create_backup_script(
            python_path, manage_py, backup_dir, max_backups
        )
        
        # Write backup script to file
        script_path = os.path.join(project_dir, 'automated_backup.sh')
        with open(script_path, 'w') as f:
            f.write(backup_script)
        
        # Make script executable
        os.chmod(script_path, 0o755)
        
        # Create cron job
        cron_job = f"{cron_schedule} {script_path} >> {project_dir}/backup.log 2>&1"
        
        self.stdout.write(
            self.style.SUCCESS(f'✅ Automated backup system configured!')
        )
        self.stdout.write(f'📅 Schedule: Every {interval}')
        self.stdout.write(f'📁 Backup directory: {full_backup_dir}')
        self.stdout.write(f'🗂️  Max backups kept: {max_backups}')
        self.stdout.write(f'📝 Script created: {script_path}')
        
        self.stdout.write('\n' + '='*60)
        self.stdout.write('TO ACTIVATE AUTOMATED BACKUPS, RUN:')
        self.stdout.write('='*60)
        self.stdout.write(f'echo "{cron_job}" | crontab -')
        self.stdout.write('\nTO VIEW CURRENT CRON JOBS:')
        self.stdout.write('crontab -l')
        self.stdout.write('\nTO REMOVE AUTOMATED BACKUPS:')
        self.stdout.write('crontab -r')
        self.stdout.write('='*60)

    def get_cron_schedule(self, interval):
        """Convert interval to cron schedule format"""
        schedules = {
            '1h': '0 * * * *',      # Every hour
            '3h': '0 */3 * * *',    # Every 3 hours
            '6h': '0 */6 * * *',    # Every 6 hours
            '12h': '0 */12 * * *',  # Every 12 hours
            '24h': '0 0 * * *',     # Daily at midnight
        }
        return schedules.get(interval, '0 */6 * * *')

    def create_backup_script(self, python_path, manage_py, backup_dir, max_backups):
        """Create the automated backup shell script"""
        script = f'''#!/bin/bash
# Automated Liquor Store Backup Script
# Generated by Django management command

# Configuration
PYTHON_PATH="{python_path}"
MANAGE_PY="{manage_py}"
BACKUP_DIR="{backup_dir}"
MAX_BACKUPS={max_backups}
PROJECT_DIR="$(dirname "$MANAGE_PY")"

# Log function
log() {{
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}}

# Change to project directory
cd "$PROJECT_DIR" || exit 1

log "🚀 Starting automated backup..."

# Activate virtual environment if it exists
if [ -f "liquor_store_env/bin/activate" ]; then
    source liquor_store_env/bin/activate
    log "📦 Virtual environment activated"
fi

# Create backup
log "💾 Creating backup..."
if "$PYTHON_PATH" "$MANAGE_PY" backup_data --format json --output-dir "$BACKUP_DIR"; then
    log "✅ Backup created successfully"
else
    log "❌ Backup creation failed"
    exit 1
fi

# Clean up old backups (keep only the most recent MAX_BACKUPS)
log "🧹 Cleaning up old backups..."
cd "$BACKUP_DIR" || exit 1

# Count backup files
BACKUP_COUNT=$(ls -1 liquor_store_backup_*.json liquor_store_backup_*.zip 2>/dev/null | wc -l)

if [ "$BACKUP_COUNT" -gt "$MAX_BACKUPS" ]; then
    # Calculate how many to delete
    DELETE_COUNT=$((BACKUP_COUNT - MAX_BACKUPS))
    
    # Delete oldest backups
    ls -1t liquor_store_backup_*.json liquor_store_backup_*.zip 2>/dev/null | tail -n "$DELETE_COUNT" | xargs rm -f
    
    log "🗑️  Deleted $DELETE_COUNT old backup(s)"
else
    log "📂 $BACKUP_COUNT backup(s) found, no cleanup needed"
fi

# Calculate total backup size
TOTAL_SIZE=$(du -sh "$PROJECT_DIR/$BACKUP_DIR" 2>/dev/null | cut -f1)
log "📊 Total backup storage: $TOTAL_SIZE"

log "🎉 Automated backup completed successfully!"

# Return to original directory
cd "$PROJECT_DIR"
'''
        return script
