# Generated by Django 5.2.5 on 2025-08-27 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_stockmovement_options_product_buying_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Customer's phone number (primary identifier)", max_length=15, unique=True)),
                ('name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('email', models.EmailField(blank=True, help_text="Customer's email address (optional)", max_length=254)),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Total loyalty points earned')),
                ('points_redeemed', models.PositiveIntegerField(default=0, help_text='Total points redeemed')),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date customer joined loyalty program')),
                ('is_active', models.BooleanField(default=True, help_text='Is customer active in loyalty program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Customer',
                'verbose_name_plural': 'Loyalty Customers',
                'ordering': ['-total_points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Points Earned'), ('REDEEMED', 'Points Redeemed'), ('BONUS', 'Bonus Points'), ('ADJUSTMENT', 'Manual Adjustment')], max_length=10)),
                ('points', models.IntegerField(help_text='Positive for earned, negative for redeemed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to='store.customer')),
                ('sale', models.ForeignKey(blank=True, help_text='Related sale (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sale')),
            ],
            options={
                'verbose_name': 'Point Transaction',
                'verbose_name_plural': 'Point Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
