# Generated by Django 5.2.5 on 2025-08-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_pointtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('MPESA', 'M-Pesa'), ('CARD', 'Card'), ('BANK', 'Bank Transfer'), ('LOYALTY_POINTS', 'Loyalty Points')], default='CASH', max_length=15),
        ),
    ]
